version "4.14"

#include "zscript/old_redline.zsc"
#include "zscript/old_psg.zsc"
#include "zscript/old_majestic.zsc"
#include "zscript/old_rearview_mirror.zsc"
#include "zscript/OldArcanumHandler.zsc"
#include "zscript/OldSpellBrain.zsc"
#include "zscript/OldArcanumSpell.zsc"
#include "zscript/OldArcanumSigil.zsc"
#include "zscript/OldArcanumTome.zsc"
#include "zscript/old_teleporter.zsc"
#include "zscript/engine_redline.zsc